{
 "title": "New dashboard6",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Solicitudes GET",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{path=\"/tasks\", method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasa de consumo de CPU del contenedor de la app por segundo",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image=\"node-hello-app\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumo de memoria del contenedor en megabytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"node-hello-app-1\"}) / 1048576\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}